### ISSUE TITLE
Gene score computation to nf-core subworkflow

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/nanostring#106]
### Description of feature

Gene Score computation --> should be subworkflow within nf-core subworkflows and then be contributed to differentialabundance and/or can be used in both pipelines equivalently :)

**Comment by nschcolnicov** [comment]
@apeltzer Just to clarify, do you want us to convert the COMPUTE_GENE_SCORES module into a single module subworkflow? Or were you envisioning something else?

**Comment by apeltzer** [comment]
Honestly speaking it might even make sense to make this a two - step process:

* Computing a gene score based on a matrix
* Visualizing it in a heatmap
This could then also be used in other pipelines more easily and re-imported here to work in nanostring 👍🏻

**Comment by apeltzer** [comment]
I agree, lets do this and I will also check the diffabundance solutions. There might be some silght differences there too, so maybe not ideal to try to do both in a single subworkflow.

**Comment by nschcolnicov** [comment]
nf-core/modules part will be addressed in this PR: https://github.com/nf-core/modules/pull/7107
nf-core/nanostring part will be addressed in this PR (once the other one gets merged): https://github.com/nf-core/nanostring/pull/114

**Comment by nschcolnicov** [comment]
Linting is failing with a weird error, waiting on a response from nf-core

**Comment by nschcolnicov** [comment]
The response I got from nf-core was that these modules weren't good candidates for migrating them to nf-core as they are not really tools but single scripts which are only hosted in the pipeline. Instead, I kept all of the work I did for standardizing the modules and subworkflow and merged that into the pipeline. The modules and new subworkflow will remain local, but they are following nf-core standards
