### ISSUE TITLE
Annotated non-HK-normalized tables not exported / published.

### ISSUE THREAD

**Issue by christopher-mohr** [nf-core/nanostring#118]
### Description of the bug

The HK-normalized annotated tables are not published in the corresponding `annotated_tables` directory when using version `1.3.0`. This still worked in the previous version. 

### Command used and terminal output

```console

```

**Comment by nschcolnicov** [comment]
@atrigila @alanmmobbs93 Looking into this

**Comment by nschcolnicov** [comment]
Hi @christopher-mohr, I'm looking at the release [PR for version 1.3.0 ](https://github.com/nf-core/nanostring/pull/75) and I don't see any changes related to `annotated_tables`  or to the publishDir directives for that module.
Also, I'm reviewing the outputs from this module:
```
    output:
    tuple val(meta), path("*ENDO.tsv"), emit: annotated_endo_data
    tuple val(meta), path("*HK.tsv*") , emit: annotated_hk_data
    tuple val(meta), path("*_mqc.tsv"), emit: annotated_data_mqc
    path "versions.yml"               , emit: versions`

```
And the publishDir directive:
```
withName: CREATE_ANNOTATED_TABLES {
        publishDir = [
            path: { "${params.outdir}/annotated_tables" },
            mode: params.publish_dir_mode,
            saveAs: { filename -> filename.equals('versions.yml') || filename.contains('_mqc') ? null : filename }
        ]
    }
```
Neither of these have changed across 1.3.0, 1.2.1 or dev.

Running the test_full profile produced this output:
```
results/annotated_tables/
├── counts_Norm_GEX_ENDO.tsv
└── counts_Norm_GEX_HK.tsv
```
Which looks ok in my opinion, could you share the command that you used, and describe what file you see missing?

**Comment by christopher-mohr** [comment]
Hi @nschcolnicov, Thanks for having a look at this.

The call I used is the following (sorry for not providing that right away):

```
nextflow run nf-core/nanostring -r 1.3.0 
    -profile bi,cluster 
    --input some_input_path
    --outdir some_output_path
```

With version `1.2.1` the `annotated_tables` directory looked like the following:

```
xxx_normalized_counts_wo_HKnorm_Norm_GEX_ENDO.tsv
xxx_normalized_counts_wo_HKnorm_Norm_GEX_HK.tsv
xxx_normalized_counts_Norm_GEX_ENDO.tsv
xxx_normalized_counts_Norm_GEX_HK.tsv
```

So actually it is the "wo_HKnorm" files that seem to be missing there. I also did not see any directly related changes to that now. I can check again later.
