### ISSUE TITLE
Provide annotated Normalized Counts after Nacho Norm

### ISSUE THREAD

**Issue by apeltzer** [nf-core/nanostring#13]

**Comment by christopher-mohr** [comment]
This should also be done with the last merged PR. Currently there will be four resulting TSV files:

```
*_normalized_counts_Norm_GEX_HK.tsv
*_normalized_counts_Norm_GEX_ENDO.tsv
*_normalized_counts_wo_HKnorm_Norm_GEX_HK.tsv
*_normalized_counts_wo_HKnorm_Norm_GEX_ENDO.tsv
```

with the provided metadata.

**Comment by christopher-mohr** [comment]
With the currently open PR all of these tables will also be added to the MultiQC report.

**Comment by apeltzer** [comment]
I think this is sufficient too!
